[package]
name = "axum-error-handler"
version = "0.1.1"
edition = "2021"
authors = ["David Yen <david99900@gmail.com>"]
description = "A simple error handler for axum"
license = "MIT"
repository = "https://github.com/MRDavidYen/axum-error-handler"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.79", features = ["full"] }
quote = "1.0.37"
proc-macro2 = "1.0.87"

[dev-dependencies]
tokio = { version = "1.40.0", features = ["full"] }
axum = "0.7.6"
thiserror = "1.0.64"
serde_json = "1.0.128"