[package]
name = "axum-error-handler"
version = "0.2.1"
edition = "2024"
authors = ["David Yen <david99900@gmail.com>"]
description = "A simple error handler for axum"
license = "MIT"
repository = "https://github.com/MRDavidYen/axum-error-handler"
categories = ["web-programming"]
keywords = ["axum", "error", "handler", "web", "framework"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.101", features = ["full"] }
quote = "1.0.40"
proc-macro2 = "1.0.87"

[dev-dependencies]
tokio = { version = "1.45.1", features = ["full"] }
axum = "0.8.4"
thiserror = "2.0.12"
serde_json = "1.0.140"
